### PR TITLE
Fix for gnome-shell 3.22

### PR DESCRIPTION
**Pull request by mmuman**
This makes it work again in gnome-shell 3.22.

### CODE REVIEW

**Comment by saysilence** [comment]
wow. somebody still using that? :)

**Comment by mmuman** [comment]
You mean, gnome-shell or this extension? 😁

**Comment by saysilence** [comment]
Heh. Both i think.=_= 
I left gnome-crapland years ago but from what i see on the net there is virtually no improvment. So sad how they killed linux desktop....

As a long time linux user i never dreamed i would say this but... Windows 10 is heavens better than gnome-(s)hell.

**Comment by mmuman** [comment]
Well, I spent 5y with gnome-flashback on Debian Sid, but metacity was crashing quite often, so I thought I'd give gnome-shell another chance. After spending a week configuring all the extensions required to get it to a usable state I kind of got used to it. It still misses basic things like accelerator keys in the window menu...
As for the extension, it's not really usable for real work, but it's a nice wow effect :-)

**Comment by mmuman** [comment]
Just found this, maybe it will save some JS nightmares to some of us https://github.com/p-e-w/argos ;-)

**Pull request merged**
